apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kf-kcc-admin # {"type":"string","x-kustomize":{"setBy":"kpt","setter":{"name":"gcloud.core.project","value":"kf-kcc-admin"}}}
resources:
- ../../upstream/management/cluster
patchesStrategicMerge:
- cluster.yaml
- nodepool.yaml
