# The purpose of this file is to store values in setters
# so its easy to get them using yq for use in Make.
# TODO(jlewi): File a feature request to have kpt list-setters return the value
project: kf-kcc-admin # {"type":"string","x-kustomize":{"setBy":"kpt","partialSetters":[{"name":"gcloud.core.project","value":"kf-kcc-admin"}]}}
name: kf-community-admin # {"type":"string","x-kustomize":{"partialSetters":[{"name":"name","value":"kf-community-admin"}]}}
location: us-central1 # {"type":"string","x-kustomize":{"partialSetters":[{"name":"location","value":"us-central1"}]}}
