# TODO(jlewi): Editor permission is probably overly broad
# now that automation is mostly in place. Should
# probably downscope this; e.g. logging, and access
# to individual namespaces.
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: kf-infra-gitops-editor-karlschriek
spec:
  member: user:kschriek@gmail.com
  role: roles/editor
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: kf-infra-gitops

---

# Create a workload identity binding for the kf-autobot GSA to autobot KSA
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: kf-autobot-workload-identity-user
spec:
  member: serviceAccount:kf-infra-gitops.svc.id.goog[kf-autobot/kf-autobot]
  role: roles/iam.workloadIdentityUser
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: kf-autobot

---

# The GSA kf-autobot needs to be able to read the secret containing autobot@kubeflow.org
# credentials
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: kf-autobot-secret-accessor
spec:
  member: serviceAccount:kf-autobot@kf-infra-gitops.iam.gserviceaccount.com
  role: roles/secretmanager.secretAccessor
  resourceRef:
    apiVersion: secretmanager.cnrm.cloud.google.com/v1beta1
    kind: SecretManagerSecret
    external: projects/kf-infra-gitops/secrets/autobot-at-kubeflow-oauth
