# This is a GCP service account to be used to impersonate autobot@kubeflow.org
# We use this GSA to pull an OAuth credential stored in secret manager
# that allows us to authorize as autobot@kubeflow.org
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: kf-autobot
