# An example of an IAMPolicyMember
# Add entries to this file to gain access to the project.
# Policies should aim to adhere to the following guidelines
#  1. Grant minimal privileges necessary
#  2. Set an expiration time for your membership
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: jeremy-owner
spec:
  # replace ${PROJECT_ID?} with your project name
  member: user:jeremy@lewi.us
  # You should aim to scope down the permissions you needed
  # right now owner is needed to deploy kubeflow
  role: roles/owner
  # TODO(jlewi): This doesn't appear to work.
  # Should be available in next version of Anthos 1.3.
  #condition:
  #  title: expires_after_2020_10_01
  #  description: Expires at midnight of 2020-10-01
  #  expression: request.time < timestamp("2020-01-01T00:00:00Z")
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    # TODO(jlewi): This is the newer syntax which work in the next 
    # release of ACM
    #external: projects/gsoc-tensorboard
    external: gsoc-tensorboard