# An example of an IAMPolicyMember
# Add entries to this file to gain access to the project.
# Policies should aim to adhere to the following guidelines
#  1. Grant minimal privileges necessary
#  2. Set an expiration time for your membership
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: kimwanstpd-owner
spec:
  # replace ${PROJECT_ID?} with your project name
  member: user:kimwnasptd@arrikto.com
  # You should aim to scope down the permissions you needed
  # right now owner is needed to deploy kubeflow
  role: roles/owner
  condition:
    title: expires_after_2020_10_01
    description: Expires at midnight of 2020-10-01
    expression: request.time < timestamp("2020-01-01T00:00:00Z")
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: projects/gsoc-tensorboard