# An example of an IAMPolicyMember
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: jlewi-owner
spec:
  # replace ${PROJECT_ID?} with your project name
  member: user:jlewi@google.com
  # You should aim to scope down the permissions you needed
  # right now owner is needed to deploy kubeflow
  role: roles/owner
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: projects/gsoc-tensorboard